mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wl.domain

server:
  port: 8088

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/library-system?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  resources:
    chain:
      cache: true